# Generated by Django 5.2.7 on 2025-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('peak_date', models.DateTimeField()),
                ('rise_time', models.DateTimeField(blank=True, null=True)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('obscuration', models.FloatField(blank=True, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
