# Generated by Django 5.2.7 on 2025-11-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
