# Generated by Django 5.2.7 on 2025-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_eventfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfavorite",
            name="event_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eventfavorite",
            name="peak",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="eventfavorite",
            name="rise",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="eventfavorite",
            name="set",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="eventfavorite",
            name="transit",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
