# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_eventfavorite_event_id_alter_eventfavorite_peak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (minimum 200x200px)",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]

